### ISSUE TITLE
News Should Have RSS Icon Next To Social Icons

### ISSUE THREAD

**Issue by cwmke** [xbmc/website#11]
Under the news section, the below options exist. I believe one more iconshould be added for the rss/atom feed similar to the 2nd picture. The new website looks great! Thanks for any consideration of this.
 
![screenshot from 2017-04-01 16-34-50](https://cloud.githubusercontent.com/assets/1923967/24582620/3eb2ce9c-16f9-11e7-8964-d9c93061d862.png)

![searx me](https://cloud.githubusercontent.com/assets/1923967/24582629/7cc6b7de-16f9-11e7-8b08-5a5c79c61a1a.png)

**Comment by Razzeee** [comment]
Please take it here, this is the repo of the note old website http://forum.kodi.tv/showthread.php?tid=311023
